/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 59e4262151258047159c4e72851cace5)
interface __BaseEnv_Env {
	ENVIRONMENT: string;
	ALLOWED_ORIGINS: string;
	WORKOS_CLIENT_ID: string;
	WORKOS_ISSUER: string;
	WORKOS_TOKEN_AUDIENCE: string;
	DATABASE_URL: string;
	WORKOS_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "ALLOWED_ORIGINS" | "WORKOS_CLIENT_ID" | "WORKOS_ISSUER" | "WORKOS_TOKEN_AUDIENCE" | "DATABASE_URL" | "WORKOS_API_KEY">> {}
}

// Module scope prevents Worker bindings from augmenting desktop ProcessEnv.
export type WorkerEnv = Env;
