import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Store } from '../server/store.js';
import { HOST_TEST_PROJECT } from '../shared/engines.js';

// A project id is generated by the application and never accepted from anyone,
// so a saved registry row that names the reserved host project, or an id that
// is not one plain folder name, was not written by this application.
const roots: string[] = [];
afterEach(async () => {
  for (const root of roots.splice(0)) await fs.rm(root, { recursive: true, force: true });
});

async function storeWithRegistry(rows: unknown[], stateFor?: string) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'diomedes-registry-guard-'));
  roots.push(root);
  const dataDir = path.join(root, 'data');
  await fs.mkdir(dataDir, { recursive: true });
  await fs.writeFile(path.join(dataDir, 'registry.json'), JSON.stringify(rows));
  if (stateFor) {
    // Even a complete, well-formed state file does not make the row openable.
    const folder = path.join(dataDir, 'projects', stateFor);
    await fs.mkdir(folder, { recursive: true });
    await fs.writeFile(path.join(folder, 'state.json'), JSON.stringify({ project: { id: stateFor } }));
  }
  return new Store(dataDir, path.join(root, 'projects'));
}

const REFUSAL = /names an id this build will not open/;

describe('a saved project registry is read as data, not trusted as a path', () => {
  it('refuses a row that names the reserved host project', async () => {
    const store = await storeWithRegistry(
      [{ id: HOST_TEST_PROJECT, name: 'Forged', folder: 'C:/anywhere' }],
      HOST_TEST_PROJECT,
    );
    await expect(store.init()).rejects.toThrow(REFUSAL);
  });

  it.each([
    ['a parent-folder traversal', '../../outside'],
    ['a Windows traversal', '..\\..\\outside'],
    ['an absolute path', 'C:/Windows'],
    ['a name that starts with a dot', '.hidden'],
    ['an empty id', ''],
    ['an id longer than a folder name should be', 'a'.repeat(65)],
  ])('refuses %s as a project id', async (_label, id) => {
    const store = await storeWithRegistry([{ id, name: 'Forged', folder: 'C:/anywhere' }]);
    await expect(store.init()).rejects.toThrow(REFUSAL);
  });

  it.each([
    ['a missing id', { name: 'Forged' }],
    ['a numeric id', { id: 42, name: 'Forged' }],
    ['a null row', null],
  ])('refuses %s', async (_label, row) => {
    const store = await storeWithRegistry([row]);
    await expect(store.init()).rejects.toThrow(REFUSAL);
  });

  it('never puts the refused id into the message a person or a log would carry', async () => {
    const store = await storeWithRegistry([{ id: '../../secret-folder', name: 'Forged' }]);
    await expect(store.init()).rejects.toThrow(
      expect.objectContaining({ message: expect.not.stringContaining('secret-folder') }),
    );
  });

  it('still opens an empty registry and every project the application itself makes', async () => {
    const store = await storeWithRegistry([]);
    await store.init();
    const made = await store.createProject('Registry guard');
    expect(made.id).toMatch(/^[a-f0-9]{12}$/);
    const again = new Store(store.dataDir, store.projectRoot);
    await again.init();
    expect((await again.projects()).map((row) => row.id)).toEqual([made.id]);
  });
});
